let greenGuy = new Image(640, 128);
greenGuy.src = './assets/greenGuy.png';
// let title = new Image(1024, 640);
// title.src = './assets/title.png';
// let tiles = new Image(1024, 64);
// tiles.src = './assets/tiles.png';
// let inserterSlide = new Image(1024, 640);
// inserterSlide.src = './assets/inserterSlide.png';
// let inserterImg = new Image(96, 96);
// inserterImg.src = './assets/inserter.png';
// let playerImg = new Image(896, 64);
// playerImg.src = './assets/player.png';
// let playerJump = new Image(576, 64);
// playerJump.src = './assets/jump.png';
// let cards = new Image(768, 160);
// cards.src = './assets/cards.png';
// let items = new Image(128, 64);
// items.src = './assets/items.png';
// let gameOver = new Image(448, 200);
// gameOver.src = './assets/gameover.png';
// let sound = document.getElementById("sound");
// sound.loop = false;
// sound.play();
// let sound2 = document.getElementById("sound2");
// sound2.loop = true;
// sound.onended = function() {
//     sound2.play();
// };